### ISSUE TITLE
simulate_expression.R - fasta with short names referred to

### ISSUE THREAD

**Issue by blakeb211** [mikelove/swimdown#2]
The file
simulate_expression.r refers to 
`fasta <- "gencode.v28.transcripts.short.names.fa"`

It is not clear how the names were shortened, but errors from running the script suggest that it might be important.

Could you indicate how the names were shortened?

I have downloaded and un-gzipped this file as my best guess for source file that the file above was derived from: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.transcripts.fa.gz

**Comment by mikelove** [comment]
These were just shortened at the transcript name. GENCODE also adds metadata on the header line in their FASTA files. Salmon could shorten these internally when you use `--gencode` but kallisto did not (at least when we were running it).

Let me know if you have any issues, I can also dig up that file and post it.

**Comment by mikelove** [comment]
The transcript names you are trying to create are listed in these quantification files, if you want to take a look:

https://zenodo.org/record/1291522#.ZF1mN3bMIaM

**Comment by blakeb211** [comment]
Lovely, that worked for me.

**Comment by mikelove** [comment]
If you have any questions about the dataset, I'm happy to talk it over.
